# Generated by Django 3.0.6 on 2020-05-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsites', '0002_auto_20200521_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesite',
            name='cell_idle_srxlev',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='basesite',
            name='nonce',
            field=models.BigIntegerField(),
        ),
    ]
