# Generated by Django 3.0.6 on 2020-05-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsites', '0003_auto_20200521_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesite',
            name='creatTime',
            field=models.CharField(max_length=64),
        ),
    ]
