# Generated by Django 3.0.6 on 2020-05-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsites', '0004_auto_20200521_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcc', models.IntegerField()),
                ('mnc', models.IntegerField()),
                ('lac', models.IntegerField()),
                ('ci1', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
