# Generated by Django 3.0.6 on 2020-06-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsites', '0007_celllocation_signalrange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celllocation',
            name='mcc',
            field=models.IntegerField(default=460),
        ),
    ]
