# Generated by Django 3.0.6 on 2020-06-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsites', '0008_auto_20200609_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celllocation',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='celllocation',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
    ]
