# Generated by Django 3.0.6 on 2020-06-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsites', '0010_auto_20200612_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcc', models.IntegerField(default=460)),
                ('mnc', models.IntegerField()),
                ('lac', models.IntegerField()),
                ('coverage', models.TextField(blank=True)),
            ],
        ),
    ]
